### ISSUE TITLE
Bereits ausgeliehene Ordner weitergeben

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/moozean#1]
Wenn man einer Person einen Ordner ausleiht, der schon ausgeliehen ist, dann sollte der Ordner weitergegeben werden. Dadurch wird verhindert, dass Ordner nicht gleichzeitig an 2 Leute ausgeliehen sind und man muss auch nicht lange zurückgeben und wieder ausleihen. 

Hier sollte aber erst eine Warnung angezeigt werden, bevor der Ordner weitergegeben wird, nicht dass man das gar nicht möchte und dies noch nicht einmal mitbekommt.

**Comment by Sedrunum** [comment]
fixes #30

**Comment by Sedrunum** [comment]
fixes #35
