### ISSUE TITLE
Kategorien bei Studienfach überprüfen

### ISSUE THREAD

**Issue by mathivierpunktnull** [FachschaftMathPhys/moozean#107]
Alte unnötige Kategorien zusammenfassten (Lehramt Beifach, ohne Beifach) und neue hinzufügen (Physik Bachelor, Mathe Bachelor, Mathe Master und weitere).

**Comment by henrixapp** [comment]
Geht unter https://moozean.mathphys.stura.uni-heidelberg.de/moor/management
