### ISSUE TITLE
Suche nach Prüfungsdatum

### ISSUE THREAD

**Issue by Sedrunum** [FachschaftMathPhys/moozean#16]
Können wir implementieren, dass man nur die reports angezeigt bekommt, deren Prüfungsdatum hinter einem auswähbarem Datum liegt? (War/ist ein Feature im alten Moor)

**Comment by henrixapp** [comment]
Sollte möglich sein. Wie wäre es eine Zeitspanne?

**Comment by Sedrunum** [comment]
Ja, warum nicht. https://github.com/cibernox/ember-power-calendar ?

**Comment by henrixapp** [comment]
In master (moor/report) benutzen wir schon eine custom pikaday componente

**Comment by henrixapp** [comment]
Sollte das nicht mit 3b19b7cf21bb028cf2f77ee7fa5a27acbf39d42b  geschlossen sein?

**Comment by Sedrunum** [comment]
yep
