### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by joker234** [FachschaftMathPhys/moozean#30]
to be converted in single issues:
* kann nicht auf Continue klicken
* Man kann Ordner mehrfach ausleihen
* nicht mit Tastatur zu bedienen → kann nicht mit Pfeiltasten Studi auswählen und RETURN drücken
* „Allgemein“ braucht viel zu lange zum laden
* die linke Navbar lässt sich links-rechts verschieben (horizont. Scrollbar)
* kann Studi nicht löschen
* Mail ging nicht raus

**Comment by henrixapp** [comment]
Danke fürs FeedbacckDer Mailausgangsserver ist nicht öffentlich, nur ein Mailcatcher....

**Comment by Sedrunum** [comment]
duplicate now
