### ISSUE TITLE
ER-Diagramm hochladen

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/moozean#4]
Es wurde mal ein ER-Diagramm erstellt. Dies könnte man wieder/weiterverwenden. Dafür wäre es perfekt, wenn man es hier hochladen würde.

**Comment by Sedrunum** [comment]
Habe mal das ERD geupdatet.

**Comment by Sedrunum** [comment]
Wiki hat nun zwei Links als SVG und PNG
