### ISSUE TITLE
Pfand kassieren

### ISSUE THREAD

**Issue by OccamsBeard** [FachschaftMathPhys/moozean#6]
Falls ein Studi, der noch kein Pfand bezahlt hat, einen pfandpflichtigen Ordner ausleiht, soll mit dem Inaktivwerden des Ausleihen-Buttons direkt die Möglichkeit entstehen, Pfand zu kassieren. Das könnte durch einen Dialog realisiert werden.

**Comment by henrixapp** [comment]
Implementiert in 6f65db2413566ca0589c87417116584b0e7a1ccd . Sollte aber ein expliziter Dialog werden, der speziell Anweisungen erteilt...

**Comment by ethylomat** [comment]
Ja, es wär praktisch, wenn man den Ablauf mit Kassenbuch und so stichpunktartig ausführt. Insbesondere für neue Fachschaftler.
