### ISSUE TITLE
Pfand zurückbekommen

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/moozean#61]
Beim Bearbeiten von Studierenden sollte es die Möglichkeit geben festzuhalten, ob die Studierende Person ihr Pfand bereits zurückerhalten hat. Derzeit ist es nicht möglich festzustellen ob noch Geld ausgezahlt werden kann, oder dies bereits getan wurde.

**Comment by Sedrunum** [comment]
fixed by 6f3f20b1a8f2f13e9ebe5670aa864306dc94fbd6
