### ISSUE TITLE
Limit in der Suche

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/moozean#63]
Die Suche darf nicht mehr als 10 Berichten anzeigen.

Derzeit ist der Server überfordert, da per default vermutlich alle Berichte aus der Datenbank geholt werden.

**Comment by henrixapp** [comment]
https://guides.emberjs.com/v2.16.0/models/handling-metadata/ und
https://github.com/cerebris/jsonapi-resources/issues/126

**Comment by henrixapp** [comment]
Fixed by 674a90dfd940824dc9bd983173c41f896fa913cd
