### ISSUE TITLE
Studierendes bearbeiten abbrechn

### ISSUE THREAD

**Issue by ThorstenBuss** [FachschaftMathPhys/moozean#64]
Wenn man unter Studierende jemanden bearbeitet und anschließend auf abbrechen klickt, wird die Änderung dennoch angezeigt bis die Seite neu geladen wird. Ähnliches passiert manchmal auch unter Ausleihe.

**Comment by Sedrunum** [comment]
fixed. Hatte ein promise aufzulösen und rollbackAttributes() statt rollback() zu verwenden, da nur Attribute verändert. Fix kommt im nächsten Commit
