### ISSUE TITLE
Prüfungsberichte suchen Ergebnisseiten

### ISSUE THREAD

**Issue by ThorstenBuss** [FachschaftMathPhys/moozean#65]
Wenn die Ergebnisse auf n Seiden verteilt werden kann man die Seiten 0-(n-1) statt von 1-n abrufen.

**Comment by Sedrunum** [comment]
immer noch?

**Comment by ThorstenBuss** [comment]
Hab es gerade getestet. Scheint nicht mehr so zu sein.

**Comment by henrixapp** [comment]
Kann man schließen?
