### ISSUE TITLE
"zuletzt zurückgegebene Ordner" funktioniert nicht

### ISSUE THREAD

**Issue by SinForest** [FachschaftMathPhys/moozean#69]
Die Seite "zuletzt zurückgegebene Ordner" funktioniert nicht.
a) neue Einträge erscheinen nicht
b) der Eintrag "Studierendes" fehlt bei alle bereits vorhandenen Einträgen

**Comment by Sedrunum** [comment]
im nächsten Commit wird die Spalte Studierendes wieder funktionieren und die Leichen hoffentlich von Menschen mit genug Rechten auf dem FS-Server gelöscht worden sein
