### ISSUE TITLE
Schöneres Favicon / Titel

### ISSUE THREAD

**Issue by SinForest** [FachschaftMathPhys/moozean#70]
Der Moozean lässt sich in einer vollen Tab-Leiste nur schwer von anderer FS-Software unterscheiden. Wenn er schon sein eigenes Logo hat, könnte er dieses ja auch als Favicon nutzen.
Außerdem ist der HTML-Titel der Seite noch "EmberOzean", das soll vermutlich nicht so bleiben.

**Comment by Sedrunum** [comment]
fixed, kommt im nächsten Commit
