### ISSUE TITLE
Uniid faken

### ISSUE THREAD

**Issue by henrixapp** [FachschaftMathPhys/moozean#74]
Bei leuten die pfand bezahlt haben, aber keine UniID angegeben hatten, sind im aktuellen System nicht berücksichtigt.

**Comment by Sedrunum** [comment]
diese Menschen wurden nicht übernommen? Warum haben wir einfach keine Standard-ID bei der Migrierung übernommen bspw. aa000

**Comment by henrixapp** [comment]
weil sie unique ist

**Comment by Sedrunum** [comment]
validation macht nun uniqueness nicht mehr und es existiert die Möglichkeit, 00007 Agenten in den Dienst ihrer Majestät aufzunehmen
