### ISSUE TITLE
Serve Fonts properly

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/moozean#79]
I believe that it is not a big problem to serve fonts locally without using google fonts. Please implement this.

**Comment by Sedrunum** [comment]
hopefully done

**Comment by samuscherer** [comment]
Was probably fixed in https://github.com/FachschaftMathPhys/moozean/commit/53efd30584378cf1ffb5b4067f364b48cd63c858 and/or https://github.com/FachschaftMathPhys/moozean/commit/51252be7dc1617157731cc2894d52278413cf3e9

Issue should therefore be closed (@Sedrunum or @henrixapp).
