### ISSUE TITLE
Bericht eintragen funktioniert nicht

### ISSUE THREAD

**Issue by TomTomRixRix** [FachschaftMathPhys/moozean#84]
Warum auch immer, wenn ich auf speichern klicke, passiert nichts. Ich bekomme zumindest kein Feedback, ob
* der Upload erfolgreich war
* der Upload fehlgeschlagen ist
* der Upload gerade noch im Gange ist und ich einfach nur warten muss

Ich kann leider nicht sagen, woran das liegt, aber ihr könnt ja mal versuchen es mit den folgenden Daten zu reproduzieren:
* Studienfach: Klausur
* Prüfungstyp: Mathematik
* Prüfende: Denis Vogel
* Modul: Elementare Zahlentheorie
* Odernerreihe: KM2
* Prüfungsdatum: 11. 2. 2015
* und einer PDF

**Comment by henrixapp** [comment]
Problem ist, dass kein Datum angegeben wird, bzw. die Komponente `paper-pikaday` kein ISO-String liefert.

**Comment by henrixapp** [comment]
Fixed by 360fd69a071b8c39b3f413a5f73cb3ad09660125
