### ISSUE TITLE
Berichte nach Eintragen automatisch drucken

### ISSUE THREAD

**Issue by tynsh** [FachschaftMathPhys/moozean#87]
Ordnerreihen sollten ein neues Attribut Exemplare bekommen.

Berichte sollten nach dem Eintragen über "Berichte Eintragen" oder "Mails bearbeiten" automatisch gedruckt werden.
Anzahl der Kopien sollte die Anzahl der ausgewählten Ordnerreihen mal Exemplare sein.

**Comment by henrixapp** [comment]
zu 1.)
Ordnerreihen haben eine bestimmte anzahl von ordnern. Wäre doppelt.
zu 2.)
Wie wäre es mit einer Checkbox und anzahl der exemplarezähler. Des Weiteren wäre ein Redirect auf den Ordner sinnvoll.

**Comment by henrixapp** [comment]
Related to #94

**Comment by Sedrunum** [comment]
cf23977d8fa43033d658fd26c8cea33f87763500

**Comment by Sedrunum** [comment]
Dialog erstellt/eingefügt
