### ISSUE TITLE
Zeitleiste

### ISSUE THREAD

**Issue by TheEbolaDoc** [FachschaftMathPhys/moozean#95]
Die Zeitleiste sollte nicht 1970 anfangen :D 1997 dürfte reichen

**Comment by friedz** [comment]
Wäre es vielleicht möglich die beim ältesten Bericht anfangen zu lassen

**Comment by Sedrunum** [comment]
habe jetzt das früheste Datum auf den 01.01.1984 gesetzt, da der erste Bericht in diesem Monat lag.
