### ISSUE TITLE
Autroreload nach 5Minuten

### ISSUE THREAD

**Issue by Sedrunum** [FachschaftMathPhys/moozean#98]
Es sollte die Möglichkeit geben, dass die Ansicht der ausgeliehenen Ordner auf der Startseite nach regelmäßigen zeitlichen Abständen aktualisiert wird.

**Comment by henrixapp** [comment]
Dies wäre mit Websockets/ actioncable möglich --> Kummerkasten zeigt dies bei der Importfunktion

**Comment by Sedrunum** [comment]
Autoreload alle 30s sollte implementiert sein.
